name: Merging Pipeline

on: 
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchorize]

jobs: 
  a_test_job:
    runs-on: ubuntu-20.04
    steps: 
      - uses: actions/checkout@v2
      - name: github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        run: echo "$COMMIT_MESSAGES"
  check-frontend:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: npm install
        run: cd tvt-sanasto-frontend&&npm install
      - name: eslint
        run: npm run eslint
      - name: build
        run: npm run build
